services:
    redis:
        container_name: cinema-redis
        image: redis:6.2.5-alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
